### ISSUE TITLE
URL_HOST for local use

### ISSUE THREAD

**Issue by JosephSamela** [podify-org/podify#52]
What should the `URL_HOST` be for running locally?

I'm attempting to run podify on a local server using the [docker-compose.example.yml](https://github.com/podify-org/podify/blob/master/docker/docker-compose.example.yml). In my docker-compose I set the `URL_HOST` environment variable to the server address `192.168.1.5`, like this:

```
URL_HOST: http://192.168.1.5
```

When I navigate to the webpage, I get this basic login screen. I login using the `INITIAL_USER_EMAIL` which seems to succeed, but then I get a blank screen. Any idea how to fix this? Thanks!

![image](https://user-images.githubusercontent.com/16111451/162486868-2deddd4f-eeea-437a-822c-69e33d164da6.png)

![image](https://user-images.githubusercontent.com/16111451/162487416-fc4c06ee-635a-4e2a-91de-1e138bb4d271.png)

**Comment by maxhollmann** [comment]
You probably just need to set it to `URL_HOST: http://192.168.1.5:3000`, otherwise it'll try to request the JS and CSS assets from port 80 which nothing is listening on.

If it still doesn't work after that, can you open the network tab in the developer tools in the browser (F12 usually), reload the page, and send a screenshot of that?

**Comment by JosephSamela** [comment]
Yup, I was missing the port and the app was making requests to `:80` causing the broken pages. I changed to `URL_HOST: http://192.168.1.5:3000` and it loads up correctly. Thanks for the help!
